# Generated by Django 3.2.6 on 2021-08-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='rentalrate',
            name='daily_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='real_cost',
            field=models.IntegerField(),
        ),
    ]
