# Generated by Django 3.2.6 on 2021-08-19 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_auto_20210818_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rent.customer'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='rental',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rent.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehiclesize',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
