# Generated by Django 3.2.6 on 2021-08-19 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_auto_20210819_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.vehiclesize'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.vehicletype'),
        ),
    ]
