# Generated by Django 3.2.6 on 2021-08-19 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_auto_20210819_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='daily_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rent.rentalrate'),
        ),
    ]
