# Generated by Django 3.2.6 on 2021-08-19 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_rental_daily_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='daily_rate',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='real_cost',
        ),
    ]
