# Generated by Django 3.2.6 on 2021-08-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_auto_20210819_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='real_cost',
            field=models.IntegerField(null=True),
        ),
    ]
