# Generated by Django 3.2.6 on 2021-08-17 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=80)),
                ('model_name', models.CharField(max_length=80)),
                ('color', models.CharField(max_length=80)),
                ('milage', models.IntegerField()),
                ('top_speed', models.IntegerField(default=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.person')),
            ],
        ),
        migrations.CreateModel(
            name='ImageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
            ],
        ),
    ]
