# Generated by Django 3.2.6 on 2021-08-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='passengers',
            field=models.ManyToManyField(related_name='in_cars', to='main.Person'),
        ),
    ]
