# Generated by Django 3.2.6 on 2021-08-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='gifs',
        ),
        migrations.AddField(
            model_name='gif_model',
            name='category',
            field=models.ManyToManyField(blank=True, to='gifs.Category'),
        ),
    ]
