# Generated by Django 3.2.6 on 2021-08-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0003_remove_gif_model_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='gif_model',
            name='categories',
            field=models.ManyToManyField(to='gifs.Category'),
        ),
    ]
