# Generated by Django 3.2.6 on 2021-08-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='contract_type',
            field=models.CharField(choices=[('buy', 'buy'), ('rent', 'rent'), ('freehold', 'freehold')], default=(('buy', 'buy'),), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'house'), ('apartment', 'aparment'), ('apartment', 'penthouse')], default=(('buy', 'buy'),), max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='img',
            field=models.ImageField(upload_to='property'),
        ),
    ]
